[Interface]
PrivateKey = 
ListenPort = 51818
PostUp = /sbin/ip addr add dev %i fe80::1:8/128 peer fe80::8:1/128
PostUp = /sbin/ip addr add dev %i 169.254.1.8/32 peer 169.254.8.1/32
Table = off

[Peer]
PublicKey = ooMm6WV4Dh1zXA0DKT21Qudw6Y/DRkG09e4eLyU0Km0=
Endpoint = fr-rns1.flap42.eu:51881
AllowedIPs = fe80::8:1/128, 169.254.8.1/32, 172.16.0.0/12, 10.0.0.0/8, fd00::/8, ff02::1:6/128
PersistentKeepalive = 30
